name: Deploy Lambda Function

on:
  push:
    branches: -main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repo
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: | 
          sudo apt-get update
          sudo apt-get install -y awscli
      
      - name: Install Dependencies
        run: |
          pip install -r lambda_function/requriments.txt -t lamdba_function/

      - name: Zip lambda Code
        run: |
          cd lambda_function && zip -r lambda_function.zip .

      - name: Deploy to AWS Lambda
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: us-east-1
          LAMBDA_FUNCTION_NAME: s3-file-trigger
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
           --zip-file fileb://lambda_function/lambda_function.zip
